PLAYER_SPEED = 5
PLAYER_JUMP = 10
PLAYER_SHOOT_CD = 1000
PLAYER_REFLECT_CD = 1000
PLAYER_INVULNERABLE_TIME = 3000
PLAYER_ANIMATION_SPEED_IDLE = 0.1
PLAYER_ANIMATION_SPEED_ATTACK = 0.3
PLAYER_ANIMATION_SPEED_RUN = 0.3
PLAYER_ANIMATION_SPEED_AIR = 0.2
PLAYER_ANIMATION_FLICKER_ROTATION = 100
PLAYER_ANIMATION_SPEED_DIE = 0.1

WIN_WIDTH = 800 
WIN_HEIGHT = 640 
DISPLAY = (WIN_WIDTH, WIN_HEIGHT) 
BACKGROUND_COLOR = "#004400"
COLOR_FILL_SPEED = 0.3
GRAVITY = 0.5

ENEMY_WIDTH = 20
ENEMY_HEIGHT = 32
ENEMY_COLOR = "#ff0000"
ENEMY_ANIMATION_SPEED_ATTACK = 0.08

ENEMY_WEAPON_WIDTH = 5
ENEMY_WEAPON_HEIGHT = 5
ENEMY_WEAPON_COLOR = "#ffffff"
MAX_ENEMY_WEAPON_SPEED = 4
ENEMY_WEAPON_COOLDOWN = 3000
SHURIKEN_ROTATION = 100
SHURIKEN_COOLDOWN_AFTER_REFLECT = 5000

WEAPON_WIDTH = 5
WEAPON_HEIGHT = 200
WEAPON_COLOR = "#0000ff"
WEAPON_SPEED = 3

IMAGES_FOLDER = "./images/"
SOUNDS_FOLDER = "./sounds/"

NUMBER_OF_LIVES = 3
LIVE_POSITION_WIDHT = WIN_WIDTH - 100
LIVE_POSITION_HEIGHT = 5

SOUND_RUN_CD = 300
